{% set name = "chemex" %}
{% set version = "2026.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemex-{{ version }}.tar.gz
  sha256: 6cbbe652a78e5c6483691bd82afcd016ef9df134eb82261d7300dca75eeb530b

build:
  entry_points:
    - chemex = chemex.chemex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - annotated-types
    - cachetools
    - emcee
    - lmfit
    - matplotlib-base
    - numdifftools
    - numpy
    - pydantic
    - rapidfuzz
    - rich
    - scipy

test:
  imports:
    - chemex
  commands:
    - pip check
    - chemex --help
  requires:
    - pip

about:
  summary: An analysis program for chemical exchange detected by NMR
  license: GPL-3.0-only
  license_file: LICENSE.md
  home: https://github.com/gbouvignies/ChemEx

extra:
  recipe-maintainers:
    - gbouvignies
